name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20v
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: npm install  # Install dependencies including mochawesome

    - name: Run Cypress tests
      uses: cypress-io/github-action@v5
      with:
        browser: chrome
      env:
        CYPRESS_REPORTER: mochawesome
        CYPRESS_REPORTER_OPTIONS: '{"reportDir":"cypress/reports","overwrite":false,"html":true,"json":true,"embeddedScreenshots":true,"inlineAssets":true}'

    - name: Merge Mochawesome reports
      run: |
        npx mochawesome-merge cypress/reports/*.json > cypress/reports/merged-report.json
        npx marge cypress/reports/merged-report.json --reportDir cypress/reports --inline

    - name: Archive Cypress artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-artifacts
        path: |
          cypress/videos/**/*
          cypress/screenshots/**/*
          cypress/reports/**/*
