name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20v
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install Allure commandline
      run: npm install -g allure-commandline --save-dev

    - name: Run Cypress tests with Allure
      uses: cypress-io/github-action@v5
      with:
        browser: chrome

    - name: Generate Allure Report
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Archive Allure Report, Videos, and Screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-allure-artifacts
        path: |
          cypress/videos/**/*
          cypress/screenshots/**/*
          cypress/allure-report/**/*
