name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20v
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Set to latest Node.js version
        cache: 'npm'

    - name: Clear npm cache
      run: npm cache clean --force  # Clear npm cache to avoid potential issues
    # - name: Install Dependencies
    #   run: npm ci  # Use npm ci for clean installs based on package-lock.json

    - name: Run Cypress tests
      uses: cypress-io/github-action@v5
      with:
        browser: chrome  # You can specify other browsers like electron or firefox

        
    - name: Archive Cypress artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
       name: cypress-artifacts
       path: |
          cypress/videos/**/*
          cypress/screenshots/**/*
          cypress/reports/cypress-report.html