name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20v
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: npm ci  # Use npm ci for clean installs based on package-lock.json

    - name: Install Allure commandline
      run: npm install -g allure-commandline --save-dev

    - name: Run Cypress tests with Allure
      uses: cypress-io/github-action@v5
      with:
        browser: chrome
        config: allure=true  # Enable Allure plugin
      env:
        CYPRESS_VIDEO: true
        CYPRESS_SCREENSHOT_ON_RUN_FAILURE: true  # Ensure videos and screenshots are enabled

    - name: Generate Allure Report
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Archive Allure Report, Videos, and Screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-allure-artifacts
        path: |
          allure-report
          cypress/videos/**/*
          cypress/screenshots/**/*
